name: "strling index"
description: STRling (pronounced like “sterling”) is a method to detect large STR expansions from short-read sequencing data. "Index" creates a bed file of large STR regions in the reference genome. This step is peformed automatically as part of strling extract. However, when running multiple samples, it is more efficient to do it once, then pass the file to strling extract using the -g option. (https://strling.readthedocs.io/en/latest/run.html)
authors:
  - Christopher Schröder
